[package]
name = "neovide"
version = "0.8.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"
build = "build.rs"
description = "Neovide: No Nonsense Neovim Gui"
repository = "https://github.com/neovide/neovide"
resolver = "2"

[workspace]
members = ["neovide-derive"]

[features]
default = []
embed-fonts = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
neovide-derive = { path = "neovide-derive" }
euclid = "0.20.7"
lru = "0.4.3"
derive-new = "0.5"
rmpv = "1.0.0"
image = { version = "0.22.3", default-features = false, features = ["ico"] }
nvim-rs = { git = "https://github.com/KillTheMule/nvim-rs", branch = "master", features = ["use_tokio"] }
tokio = { version = "1.1.1", features = ["full"] }
tokio-util = "0.6.7"
async-trait = "0.1.18"
lazy_static = "1.4.0"
unicode-segmentation = "1.6.0"
log = "0.4.8"
flexi_logger = { version = "0.17.1", default-features = false }
parking_lot = "0.10.0"
cfg-if = "0.1.10"
which = "4"
dirs = "2"
rand = "0.7"
pin-project = "0.4.27"
futures = "0.3.12"
# We're using our own forks for winit and glutin,
# to fix some keyboard-related issues.
# This PR resolves issues with modifiers behaviour under X11
# and currenctly our glutin#neovide-x11-nt is based on it.
# https://github.com/maroider/winit/pull/6
# Previouse PR should be merged into next one:
# https://github.com/rust-windowing/winit/pull/1932
# And after this one is merged, we can use official versions.
winit = { git = "https://github.com/neovide/winit", branch = "neovide-x11-nt" }
# glutin is using this branch https://github.com/mahkoh/glutin/tree/x11-nt
# with added small patch to support KeyEvent.text_with_all_modifiers
# After it's merged upstream we should make PR with this small change.
glutin = { git = "https://github.com/neovide/glutin", branch = "neovide-x11-nt", features=["serde"] }
gl = "0.14.0"
swash = "0.1.4"
clap="2.33.3"
xdg="2.4.0"
clipboard="0.5.0"

[dev-dependencies]
mockall = "0.7.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"

[target.'cfg(linux)'.dependencies.skia-safe]
features = ["gl", "egl"]
version = "^0.42.1"

[target.'cfg(not(linux))'.dependencies.skia-safe]
features = ["gl"]
version = "^0.42.1"

[profile.release]
debug = true
lto = true
incremental = true

[package.metadata.bundle]
name = "Neovide"
identifier = "com.neovide.neovide"
icon = ["assets/neovide.ico"]
version = "0.8.0"
resources = []
copyright = "Copyright (c) Keith 2021. All rights reserved."
category = "Productivity"
short_description = "A simple GUI for Neovim."
long_description = """
This is a simple graphical user interface for Neovim. Where possible there are some graphical improvements, but it should act functionally like the terminal UI.
"""
osx_minimum_system_version = "10.11"
